---

- hosts: all

  roles:
    - docker
    - role: ssh
      tags: [ ssh ]
    - role: git
      tags: [ git ]
    - fail2ban
    - role: jenkins
      tags: [ jk ]
    - role: service-user
      tags: [ svc ]
      vars:
        svc:
          name: don
          user: don
          desc: "Miami Vice"
      tags: miami
    - role: service-user
      vars:
        svc:
          name: dudeldidu
          user: dudel
          desc: "Jodler des Tages"
      tags: [ jodel ]

  tasks:
    - name: Update pip
      apt:
        name: python3-pip
        state: latest
      become: true

    - name: Add prefect to the docker group
      user:
        name: prefect
        groups:
          - docker
          - ssh-users
        append: true
      become: true
      tags:
        - group

    - name: Add some convenience aliases for bash
      lineinfile:
        path: ~/.bash_aliases
        regex: "^alias play="
        line: "alias play=ansible-playbook"
        owner: prefect
        group: prefect
        mode: '0644'
        create: yes

    - name: Create the agent user
      user:
        name: jkagent
        comment: "Jenkins Agent"
        groups: 
          - docker
          - ssh-users
      become: true

    - name: Install a default JDK so the agent can work
      apt:
        name: default-jdk
        state: latest
      become: true

    - name: Create the jkserv user
      user:
        name: jkserv
        comment: "Jenkins Service"
        groups: 
          - docker
          - ssh-users
      become: true

    - name: Add some tools for my development
      apt:
        name:
          - vim
          - mc
      become: true
      tags: tools
