---

- hosts: all
  tasks:
    - name: Update pip
      apt:
        name: python3-pip
        state: latest
      become: true

    - name: Add apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add the docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
      become: true
      tags:
        - repo

    - name: Install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      become: true

    - name: Install Docker Module for Python
      pip:
        name: docker
